name: SimpleCommandsLegacy
main: xyz.acrylicstyle.simplecommands.SimpleCommands
version: 1.0-SNAPSHOT
depend:
  - TomeitoLib
commands:
  suicide:
    description: ""
  ping:
    description: "Shows your ping"
  pingall:
    description: "Shows everyone's ping"
    permission: simplecommands.pingall
  textures:
    description: ""
    aliases: ["texture2", "resourcepack", "resource", "/texture"]
  opme:
    description: ""
    usage: "https://freeop.yululi.xyz/"